import 'package:flutter/material.dart';
import 'package:jbmanager/models/document.dart';

const documentStates = {
  1: DocumentStatus(1, 5, 'En cours', Colors.blue),
  2: DocumentStatus(2, 5, 'Confirmé', Colors.green),
  3: DocumentStatus(3, 5, 'Échu', Colors.red),
  4: DocumentStatus(4, 6, 'En cours', Colors.blue),
  5: DocumentStatus(5, 6, 'Livrée', Colors.green),
  6: DocumentStatus(6, 6, 'Facturée', Colors.green),
  7: DocumentStatus(7, 6, 'Partiellement Facturée', Colors.orange),
  8: DocumentStatus(8, 6, 'Partiellement Livrée', Colors.orange),
  9: DocumentStatus(9, 7, 'Non Facturée', Colors.red),
  10: DocumentStatus(10, 7, 'Facturée', Colors.green),
  11: DocumentStatus(11, 7, 'Partiellement Facturés', Colors.orange),
  12: DocumentStatus(12, 7, 'Retour', Colors.purple),
  14: DocumentStatus(14, 8, 'En retard', Colors.red),
  16: DocumentStatus(16, 8, 'Partiellement payée', Colors.orange),
  17: DocumentStatus(17, 8, 'Brouillon', Colors.grey),
  18: DocumentStatus(18, 8, 'Non réglée', Colors.red),
  19: DocumentStatus(19, 8, 'Réglée', Colors.green),
  20: DocumentStatus(20, 8, 'Avoir', Colors.blueGrey),
  21: DocumentStatus(21, 13, 'Reçu', Colors.green),
  22: DocumentStatus(22, 13, 'Confirmé', Colors.green),
  23: DocumentStatus(23, 2, 'Commande reçue', Colors.blue),
  24: DocumentStatus(24, 3, 'Facturée', Colors.green),
  26: DocumentStatus(26, 5, 'Facture pro forma', Colors.blueGrey),
  27: DocumentStatus(27, 1, 'Non Envoyée', Colors.red),
  28: DocumentStatus(28, 1, 'Envoyée', Colors.green),
  29: DocumentStatus(29, 2, 'Commande reçue partiellement', Colors.orange),
  30: DocumentStatus(30, 2, 'Commande non Reçue', Colors.red),
  31: DocumentStatus(31, 3, 'Non Facturée', Colors.red),
  32: DocumentStatus(32, 4, 'Non Réglée', Colors.red),
  33: DocumentStatus(33, 4, 'Réglée', Colors.green),
  34: DocumentStatus(34, 4, 'Impayée', Colors.red),
  35: DocumentStatus(35, 7, 'Annulé', Colors.red),
  38: DocumentStatus(38, 8, 'Annulée', Colors.red),
  39: DocumentStatus(39, 3, 'Partiellement Facturée', Colors.orange),
  40: DocumentStatus(40, 8, 'Avoir réglé', Colors.green),
  41: DocumentStatus(41, 8, 'Accompte', Colors.blue),
  46: DocumentStatus(46, 4, 'Avoir fournisseur', Colors.blueGrey),
  47: DocumentStatus(47, 4, 'Acompte fournisseur', Colors.blue),
  48: DocumentStatus(48, 4, 'Avoir fournisseur réglé', Colors.green),
  49: DocumentStatus(49, 4, 'Facture fournisseur annulée', Colors.red),
  50: DocumentStatus(50, 7, 'Partiellement retourné', Colors.orange),
  51: DocumentStatus(51, 5, 'Annulé', Colors.red),
  52: DocumentStatus(52, 5, 'Demande de prix', Colors.blue),
  53: DocumentStatus(53, 5, 'Demande de prix confirmée', Colors.green),
  54: DocumentStatus(54, 5, 'Facture pro forma confirmée', Colors.green),
  55: DocumentStatus(55, 7, 'Livraison client générée par fac', Colors.blue),
  56: DocumentStatus(56, 1, 'Envoyé par mail', Colors.green),
  57: DocumentStatus(57, 7, 'Bon de spécification', Colors.blue),
  58: DocumentStatus(58, 7, 'Bon de spécification confirmé', Colors.green),
  59: DocumentStatus(59, 18, 'Réception fournisseur retournée', Colors.purple),
  60: DocumentStatus(60, 3, 'Non facturable', Colors.red),
  61: DocumentStatus(61, 3, 'Retournée', Colors.purple),
  62: DocumentStatus(62, 7, 'Non facturable', Colors.red),
  63: DocumentStatus(
    63,
    18,
    'Bon retour fournisseur avec avoir',
    Colors.purple,
  ),
  64: DocumentStatus(64, 19, 'Pré-bon de livraison', Colors.blue),
  65: DocumentStatus(65, 19, 'Pré-bon de livraison livré', Colors.green),
  66: DocumentStatus(66, 19, 'Facture BS', Colors.blueGrey),
  67: DocumentStatus(67, 8, 'Facture réglée BS', Colors.green),
  68: DocumentStatus(68, 20, 'Retour BS', Colors.purple),
  69: DocumentStatus(69, 7, 'BS retournée', Colors.purple),
  70: DocumentStatus(70, 8, 'Avoir BS', Colors.blueGrey),
  71: DocumentStatus(71, 7, 'BS retournée avec avoir', Colors.purple),
  72: DocumentStatus(72, 8, 'Facture BS réglée', Colors.green),
  73: DocumentStatus(73, 7, 'BS non facturée', Colors.red),
  74: DocumentStatus(74, 2, 'Annulée', Colors.red),
  75: DocumentStatus(75, 8, 'Facture BS annulée', Colors.red),
  76: DocumentStatus(76, 8, 'BS non facturée validée', Colors.green),
  77: DocumentStatus(77, 8, 'Devis', Colors.blue),
  78: DocumentStatus(78, 8, 'Commande', Colors.blue),
  79: DocumentStatus(79, 2, 'Annulée', Colors.red),
  80: DocumentStatus(80, 7, 'Retour avec avoir', Colors.purple),
  81: DocumentStatus(81, 4, 'Frais', Colors.blueGrey),
  82: DocumentStatus(82, 7, 'BS S2 validé', Colors.green),
  83: DocumentStatus(83, 6, 'Cmd production', Colors.blue),
  84: DocumentStatus(84, 1, 'Demande achat', Colors.blue),
  85: DocumentStatus(85, 2, 'Commande order de transfert', Colors.blue),
  86: DocumentStatus(86, 1, 'Demande achat validé', Colors.green),
  87: DocumentStatus(87, 1, 'Demande achat confirmée', Colors.green),
  88: DocumentStatus(
    88,
    1,
    'Demande achat partiellement confirmée',
    Colors.orange,
  ),
  89: DocumentStatus(89, 8, 'Facture avoir éclatée', Colors.blueGrey),
  90: DocumentStatus(90, 8, 'Facture éclatée annulée', Colors.red),
};
